#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if
  [ -z "$(git status --porcelain | grep dist)" ]
  echo "No changes to dist, change test hash $(git rev-parse HEAD)"
then
  echo "No changes to dist files"
  exit 0
fi
